version: "2"
linters:
  enable:
    - cyclop
    - decorder
    - depguard
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - gosec
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - prealloc
    - revive
    - staticcheck
    - thelper
    - unparam
    - wastedassign
    - whitespace
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/mab-go/nmea
            - gopkg.in/yaml.v2
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        path: sentence/gpgll/enum.go
      - linters:
          - lll
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
