linters:
  enable:
    - cyclop
    - deadcode
    - decorder
    - depguard
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - gocritic
    - gocyclo
    - goerr113    # NOTE: This is a good one... need to comply.
    - goimports
#    - gomnd    # NOTE: Probably not going to work since Parse functions all use segment ordinals
    - gosec
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - typecheck
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace    # NOTE: This is a good one... need to comply.
    - wrapcheck

issues:
  exclude-rules:
    - path: "sentence/gpgll/enum.go"
      linters:
        - lll
    - path: "(.+)_test\\.go"
      linters:
        - lll
