// Code generated by "enumer -type=Mode -text -linecomment -transform=first-upper -output=enum_gen.go"; DO NOT EDIT.

package gpvtg

import (
	"fmt"
	"strings"
)

const _ModeName = "ADENS"

var _ModeIndex = [...]uint8{0, 1, 2, 3, 4, 5}

const _ModeLowerName = "adens"

func (i Mode) String() string {
	i -= 1
	if i < 0 || i >= Mode(len(_ModeIndex)-1) {
		return fmt.Sprintf("Mode(%d)", i+1)
	}
	return _ModeName[_ModeIndex[i]:_ModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ModeNoOp() {
	var x [1]struct{}
	_ = x[Autonomous-(1)]
	_ = x[Differential-(2)]
	_ = x[Estimated-(3)]
	_ = x[NotValid-(4)]
	_ = x[Simulator-(5)]
}

var _ModeValues = []Mode{Autonomous, Differential, Estimated, NotValid, Simulator}

var _ModeNameToValueMap = map[string]Mode{
	_ModeName[0:1]:      Autonomous,
	_ModeLowerName[0:1]: Autonomous,
	_ModeName[1:2]:      Differential,
	_ModeLowerName[1:2]: Differential,
	_ModeName[2:3]:      Estimated,
	_ModeLowerName[2:3]: Estimated,
	_ModeName[3:4]:      NotValid,
	_ModeLowerName[3:4]: NotValid,
	_ModeName[4:5]:      Simulator,
	_ModeLowerName[4:5]: Simulator,
}

var _ModeNames = []string{
	_ModeName[0:1],
	_ModeName[1:2],
	_ModeName[2:3],
	_ModeName[3:4],
	_ModeName[4:5],
}

// ModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ModeString(s string) (Mode, error) {
	if val, ok := _ModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Mode values", s)
}

// ModeValues returns all values of the enum
func ModeValues() []Mode {
	return _ModeValues
}

// ModeStrings returns a slice of all String values of the enum
func ModeStrings() []string {
	strs := make([]string, len(_ModeNames))
	copy(strs, _ModeNames)
	return strs
}

// IsAMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Mode) IsAMode() bool {
	for _, v := range _ModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Mode
func (i Mode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Mode
func (i *Mode) UnmarshalText(text []byte) error {
	var err error
	*i, err = ModeString(string(text))
	return err
}
