// Code generated by "enumer -type=SelectionMode,FixMode -text -linecomment -transform=first-upper -output=enum_gen.go"; DO NOT EDIT.

package gpgsa

import (
	"fmt"
	"strings"
)

const _SelectionModeName = "AM"

var _SelectionModeIndex = [...]uint8{0, 1, 2}

const _SelectionModeLowerName = "am"

func (i SelectionMode) String() string {
	i -= 1
	if i < 0 || i >= SelectionMode(len(_SelectionModeIndex)-1) {
		return fmt.Sprintf("SelectionMode(%d)", i+1)
	}
	return _SelectionModeName[_SelectionModeIndex[i]:_SelectionModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SelectionModeNoOp() {
	var x [1]struct{}
	_ = x[AutomaticSelectionMode-(1)]
	_ = x[ManualSelectionMode-(2)]
}

var _SelectionModeValues = []SelectionMode{AutomaticSelectionMode, ManualSelectionMode}

var _SelectionModeNameToValueMap = map[string]SelectionMode{
	_SelectionModeName[0:1]:      AutomaticSelectionMode,
	_SelectionModeLowerName[0:1]: AutomaticSelectionMode,
	_SelectionModeName[1:2]:      ManualSelectionMode,
	_SelectionModeLowerName[1:2]: ManualSelectionMode,
}

var _SelectionModeNames = []string{
	_SelectionModeName[0:1],
	_SelectionModeName[1:2],
}

// SelectionModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SelectionModeString(s string) (SelectionMode, error) {
	if val, ok := _SelectionModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SelectionModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SelectionMode values", s)
}

// SelectionModeValues returns all values of the enum
func SelectionModeValues() []SelectionMode {
	return _SelectionModeValues
}

// SelectionModeStrings returns a slice of all String values of the enum
func SelectionModeStrings() []string {
	strs := make([]string, len(_SelectionModeNames))
	copy(strs, _SelectionModeNames)
	return strs
}

// IsASelectionMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SelectionMode) IsASelectionMode() bool {
	for _, v := range _SelectionModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for SelectionMode
func (i SelectionMode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for SelectionMode
func (i *SelectionMode) UnmarshalText(text []byte) error {
	var err error
	*i, err = SelectionModeString(string(text))
	return err
}

const _FixModeName = "123"

var _FixModeIndex = [...]uint8{0, 1, 2, 3}

const _FixModeLowerName = "123"

func (i FixMode) String() string {
	i -= 1
	if i < 0 || i >= FixMode(len(_FixModeIndex)-1) {
		return fmt.Sprintf("FixMode(%d)", i+1)
	}
	return _FixModeName[_FixModeIndex[i]:_FixModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FixModeNoOp() {
	var x [1]struct{}
	_ = x[NoFix-(1)]
	_ = x[Fix2D-(2)]
	_ = x[Fix3D-(3)]
}

var _FixModeValues = []FixMode{NoFix, Fix2D, Fix3D}

var _FixModeNameToValueMap = map[string]FixMode{
	_FixModeName[0:1]:      NoFix,
	_FixModeLowerName[0:1]: NoFix,
	_FixModeName[1:2]:      Fix2D,
	_FixModeLowerName[1:2]: Fix2D,
	_FixModeName[2:3]:      Fix3D,
	_FixModeLowerName[2:3]: Fix3D,
}

var _FixModeNames = []string{
	_FixModeName[0:1],
	_FixModeName[1:2],
	_FixModeName[2:3],
}

// FixModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FixModeString(s string) (FixMode, error) {
	if val, ok := _FixModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FixModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FixMode values", s)
}

// FixModeValues returns all values of the enum
func FixModeValues() []FixMode {
	return _FixModeValues
}

// FixModeStrings returns a slice of all String values of the enum
func FixModeStrings() []string {
	strs := make([]string, len(_FixModeNames))
	copy(strs, _FixModeNames)
	return strs
}

// IsAFixMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FixMode) IsAFixMode() bool {
	for _, v := range _FixModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for FixMode
func (i FixMode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for FixMode
func (i *FixMode) UnmarshalText(text []byte) error {
	var err error
	*i, err = FixModeString(string(text))
	return err
}
